name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          mkdir -p CCS
          cp -r Resources CCS/
          cp CCS.ps1 Functions.psm1 Listener.ps1 CCS/
          zip -r Cursor-Colors-Synchronizer.zip CCS

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: Cursor-Colors-Synchronizer.zip
